name: GitHub Readme YouTube Cards

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCaMhjN7Cq2g1cs_LRXoE5uw
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add index.html
          git commit -m "Update YouTube cards" || echo "No changes to commit"
          git push
